# Database connection configuration
# Suffix for the database name
DBNAME: pylovo_db_local
USER: postgres
HOST: localhost
PORT: 5432
PASSWORD: postgres
TARGET_SCHEMA: public
DB_SUFFIX: usa

# Logging configuration for PgReaderWriter & GridGenerator
LOG_LEVEL: INFO
LOG_FILE: "log.txt"


# EPSG code for spatial data.
# 3035 is for Europe (ETRS89-extended / LAEA Europe)
# 5070 is for USA (NAD83 / Conus Albers)
EPSG: 5070

# Data import Section
# Region Selection is done via the official US Census Bureau FIPS codes
# An overview can be found here: https://www2.census.gov/geo/docs/reference/codes/files/national_cousub.txt
# states: MA = Massachusetts, AL = Alabama, CA = California, etc.
# counties: Autauga County, 003 = Baldwin County, etc.
# count_subdivisions: Autaugaville CCD,
REGION:
  STATE: "MA"
  COUNTY: "Middlesex County"
  COUNTY_SUBDIVISION: "Cambridge city"
